"""Give the alien enemies acid attacks instead of bullets, plasma and rockets (GZDoom/UZDoom only).

Writes a DECORATE lump plus recolored projectile sprites:
  * ChaingunGuy (Spitter)       -> bursts of green acid spit instead of bullets
  * SpiderMastermind (Queen)    -> rapid acid spit instead of the chaingun
  * Arachnotron (Widow)         -> acid spit instead of plasma
  * Cyberdemon (Dragon)         -> big acid balls instead of rockets
  * Cacodemon, Mancubus, Revenant projectiles are recolored green (BAL2, MANF, FATB), and the
    Archvile's (Praetorian's) flame is recolored green (FIRE) so it reads as an acid burst.
  * Every alien bleeds green acid (BloodColor). This file holds all the alien DECORATE replacements,
    so no other WAD replaces the same class. The Spitter imp and chaingunner also name their xeno
    sounds here, so they do not depend on the DEHACKED patch reaching a replacement class.
  * Aliens killed by a big overkill (a rocket, a fuel tank) burst apart: XDeath states with TGMC's gib animations
    (sprites XG?? from build_xeno_gibs.py, xeno_gibs.wad), each with its own GibHealth.
  * Acid puddles: the acid projectiles sometimes leave a bubbling puddle (ACPD, xeno_gibs.wad) that burns for a
    few seconds with damage type "Acid"; every alien has DamageFactor "Acid", 0, so only marines and SOM burn.
  * The Lost Soul is a facehugger that runs on the floor and leaps at you (no flying, no glow), with its own
    death sound (alien/hugger_die, from alien_sounds.wad).
The imp's fireball (BAL1) is recolored by build_all.sh's green_fireball.wad; the acid reuses those sprites.

usage: build_alien_attacks.py --out OUT_DIR --freedoom FREEDOOM_ROOT --iwad IWAD
  Writes OUT_DIR/wads/alien_attacks.wad
"""
import argparse
import os
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

DECORATE = """\
// Alien attacks: generated by build_alien_attacks.py

ACTOR SpitterAcid : DoomImpBall
{
	Speed 20
	Damage 1
}

ACTOR ArachnotronAcid : DoomImpBall
{
	Speed 22
	Damage 2
}

ACTOR DragonAcid : DoomImpBall
{
	Speed 24
	Damage 8
	Scale 1.6
}

ACTOR AlienChaingunner : ChaingunGuy replaces ChaingunGuy
{
	BloodColor "30 D0 20"
	SeeSound "imp/sight"
	PainSound "demon/pain"
	DeathSound "imp/death"
	ActiveSound "imp/active"
	States
	{
	Missile:
		CPOS E 10 A_FaceTarget
		CPOS FE 4 Bright A_SpawnProjectile("SpitterAcid", 32, 0, random(-5, 5))
		CPOS F 1 A_CPosRefire
		Goto Missile+1
	}
}

ACTOR AlienQueen : SpiderMastermind replaces SpiderMastermind
{
	BloodColor "30 D0 20"
	States
	{
	Missile:
		SPID A 20 Bright A_FaceTarget
		SPID G 4 Bright A_SpawnProjectile("SpitterAcid", 36, 0, random(-6, 6))
		SPID H 4 Bright A_SpawnProjectile("SpitterAcid", 36, 0, random(-6, 6))
		SPID H 1 Bright A_SpidRefire
		Goto Missile+1
	}
}

ACTOR AlienWidow : Arachnotron replaces Arachnotron
{
	BloodColor "30 D0 20"
	States
	{
	Missile:
		BSPI A 20 Bright A_FaceTarget
		BSPI G 4 Bright A_SpawnProjectile("ArachnotronAcid", 24, 0, random(-4, 4))
		BSPI H 4 Bright
		BSPI H 1 Bright A_SpidRefire
		Goto Missile+1
	}
}

ACTOR AlienDragon : Cyberdemon replaces Cyberdemon
{
	BloodColor "30 D0 20"
	States
	{
	Missile:
		CYBR E 6 A_FaceTarget
		CYBR F 12 Bright A_SpawnProjectile("DragonAcid", 54, 0)
		CYBR E 12 A_FaceTarget
		CYBR F 12 Bright A_SpawnProjectile("DragonAcid", 54, 0)
		CYBR E 12 A_FaceTarget
		CYBR F 12 Bright A_SpawnProjectile("DragonAcid", 54, 0)
		Goto See
	}
}

ACTOR AlienSpitter : DoomImp replaces DoomImp
{
	BloodColor "30 D0 20"
	PainSound "demon/pain"
}

// The facehugger runs along the floor instead of floating, and leaps at you: a short hop toward the
// target that bites if it lands on you. (A Lost Soul's own charge keeps bouncing once it has gravity.)
// The Carrier (Pain Elemental) still spits them out; they drop to the floor.
ACTOR AlienHugger : LostSoul replaces LostSoul
{
	-FLOAT
	-NOGRAVITY
	-DONTFALL
	Radius 12
	Height 20
	Speed 12
	DeathSound "alien/hugger_die"
	States
	{
	Spawn:
		SKUL AB 10 A_Look
		Loop
	See:
		SKUL AB 3 A_Chase
		Loop
	Missile:
		SKUL C 6 A_FaceTarget
		SKUL D 0 A_StartSound("skull/melee", CHAN_VOICE)
		SKUL D 0 ThrustThingZ(0, 28, 0, 0)
		SKUL D 1 A_Recoil(-12)
		SKUL DDDDDDDDDDDDDD 1 A_JumpIfCloser(48, "Latch")
		SKUL C 6 A_Stop
		Goto See
	Latch:
		SKUL C 0 A_Stop
		SKUL C 8 A_CustomMeleeAttack(random(3, 24))
		Goto See
	Pain:
		SKUL E 3
		SKUL E 3 A_Pain
		Goto See
	Death:
		SKUL F 6
		SKUL G 6 A_Scream
		SKUL H 6
		SKUL I 6 A_NoBlocking
		SKUL JK 6
		Stop
	}
}
"""
# The other aliens only need acid blood.
for _cls, _base in [("AlienRunner", "Demon"), ("AlienStalker", "Spectre"), ("AlienShrike", "Cacodemon"),
                    ("AlienCrusher", "BaronOfHell"), ("AlienWarrior", "HellKnight"), ("AlienHunter", "Revenant"),
                    ("AlienBoiler", "Fatso"), ("AlienCarrier", "PainElemental"), ("AlienPraetorian", "Archvile")]:
    DECORATE += f"\nACTOR {_cls} : {_base} replaces {_base}\n{{\n\tBloodColor \"30 D0 20\"\n}}\n"

DECORATE += """
// A puddle of acid that falls to the floor, lies flat and burns anything standing in it (aliens are immune).
ACTOR AcidPuddle
{
	Radius 16
	Height 4
	+FLATSPRITE
	+NOTELEPORT
	+DONTSPLASH
	-NOGRAVITY
	RenderStyle Translucent
	Alpha 0.85
	DamageType "Acid"
	States
	{
	Spawn:
		ACPD A 0 NoDelay A_StartSound("acid/sizzle", CHAN_BODY, 0, 0.5)
		ACPD ABCABCABCABCABC 9 A_Explode(2, 40, XF_NOTMISSILE, false, 40)
		ACPD ABC 6 A_FadeOut(0.3)
		Stop
	}
}

// The Spitter imp's own fireball leaves a puddle half of the time.
ACTOR SpitterBall : DoomImpBall replaces DoomImpBall
{
	States
	{
	Death:
		BAL1 C 0 A_SpawnItemEx("AcidPuddle", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION, 128)
		BAL1 CDE 6 Bright
		Stop
	}
}
"""
# chance (0-255) that an acid projectile does NOT leave a puddle; the rapid-fire ones leave fewer
for _cls, _fail in [("SpitterAcid", 200), ("ArachnotronAcid", 180), ("DragonAcid", 0)]:
    _i = DECORATE.index(f"ACTOR {_cls} ")
    _end = DECORATE.index("\n}\n", _i)
    DECORATE = DECORATE[:_end] + (
        "\n\tStates\n\t{\n\tDeath:\n"
        f"\t\tBAL1 C 0 A_SpawnItemEx(\"AcidPuddle\", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION, {_fail})\n"
        "\t\tBAL1 CDE 6 Bright\n\t\tStop\n\t}") + DECORATE[_end:]

# Doom's boss monsters run A_BossDeath when they die (map specials: E1M8, MAP07, E4M8...); a gibbed one must too.
BOSSES = {"AlienCrusher", "AlienBoiler", "AlienWidow", "AlienDragon", "AlienQueen"}
# alien class -> (gib sprite from build_xeno_gibs.py or None, GibHealth)
ALIENS = {
    "AlienSpitter": ("XGSP", -40), "AlienChaingunner": ("XGSP", -40), "AlienRunner": ("XGRU", -50),
    "AlienStalker": ("XGRU", -50), "AlienShrike": ("XGSH", -80), "AlienCrusher": ("XGCR", -150),
    "AlienWarrior": ("XGWA", -120), "AlienHunter": ("XGHU", -80), "AlienBoiler": ("XGBO", -150),
    "AlienWidow": ("XGWI", -150), "AlienCarrier": ("XGCA", -120), "AlienDragon": ("XGDR", -400),
    "AlienQueen": ("XGQU", -400), "AlienPraetorian": ("XGPR", -150), "AlienHugger": (None, 0),
}


def _extend(decorate, cls, props, states):
    """Add property lines and states to the ACTOR block of `cls`."""
    start = decorate.index(f"ACTOR {cls} ")
    body_start = decorate.index("{\n", start) + 2
    end = decorate.index("\n}\n", start)
    body = decorate[body_start:end]
    if states:
        if "\tStates\n\t{\n" in body:
            cut = body.rindex("\t}")
            body = body[:cut] + states + body[cut:]
        else:
            body = body.rstrip("\n") + "\n\tStates\n\t{\n" + states + "\t}"
    return decorate[:body_start] + props + body + decorate[end:]


for _cls, (_gib, _health) in ALIENS.items():
    _props = '\tDamageFactor "Acid", 0\n'
    _states = ""
    if _gib:
        _props += f"\tGibHealth {_health}\n"
        _states = (f"\tXDeath:\n\t\t{_gib} A 4\n\t\t{_gib} B 4 A_XScream\n\t\t{_gib} C 4 A_NoBlocking\n"
                   f"\t\t{_gib} D 4\n\t\t{_gib} E 4{' A_BossDeath' if _cls in BOSSES else ''}\n"
                   f"\t\t{_gib} F -1\n\t\tStop\n")
    DECORATE = _extend(DECORATE, _cls, _props, _states)


def run(cmd):
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--freedoom", required=True)
    ap.add_argument("--iwad", required=True)
    args = ap.parse_args()
    out = os.path.abspath(args.out)
    wads = os.path.join(out, "wads")
    tmp = os.path.join(out, "alien_attacks_tmp")
    os.makedirs(wads, exist_ok=True)
    os.makedirs(tmp, exist_ok=True)
    py = [sys.executable, "-I"]

    parts = []
    for prefix in ("BAL2", "MANF", "FATB", "FIRE"):
        wad = os.path.join(tmp, f"{prefix}.wad")
        run(py + [os.path.join(HERE, "build_recolor.py"), "--freedoom", os.path.join(args.freedoom, "sprites"),
                  "--buildcfg", os.path.join(args.freedoom, "buildcfg.txt"), "--playpal", args.iwad,
                  "--prefix", prefix, "--out", wad])
        parts.append(wad)

    body = DECORATE.encode()
    deco_wad = os.path.join(tmp, "decorate.wad")
    with open(deco_wad, "wb") as f:
        f.write(struct.pack("<4sII", b"PWAD", 1, 12 + len(body)) + body + struct.pack("<II8s", 12, len(body), b"DECORATE"))
    run(py + [os.path.join(HERE, "merge_wads.py"), os.path.join(wads, "alien_attacks.wad")] + parts + [deco_wad])


if __name__ == "__main__":
    main()
