"""Give the alien enemies acid attacks instead of bullets, plasma and rockets (GZDoom/UZDoom only).

Writes a DECORATE lump plus recolored projectile sprites:
  * ChaingunGuy (Spitter)       -> bursts of green acid spit instead of bullets
  * SpiderMastermind (Queen)    -> rapid acid spit instead of the chaingun
  * Arachnotron (Widow)         -> acid spit instead of plasma
  * Cyberdemon (Dragon)         -> big acid balls instead of rockets
  * Cacodemon, Mancubus, Revenant projectiles are recolored green (BAL2, MANF, FATB), and the
    Archvile's (Praetorian's) flame is recolored green (FIRE) so it reads as an acid burst.
  * Every alien bleeds green acid (BloodColor). This file holds all the alien DECORATE replacements,
    so no other WAD replaces the same class. The Spitter imp and chaingunner also name their xeno
    sounds here, so they do not depend on the DEHACKED patch reaching a replacement class.
  * The Lost Soul (facehugger) gets its own death sound (alien/hugger_die, from alien_sounds.wad).
The imp's fireball (BAL1) is recolored by build_all.sh's green_fireball.wad; the acid reuses those sprites.

usage: build_alien_attacks.py --out OUT_DIR --freedoom FREEDOOM_ROOT --iwad IWAD
  Writes OUT_DIR/wads/alien_attacks.wad
"""
import argparse
import os
import struct
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

DECORATE = """\
// Alien attacks: generated by build_alien_attacks.py

ACTOR SpitterAcid : DoomImpBall
{
	Speed 20
	Damage 1
}

ACTOR ArachnotronAcid : DoomImpBall
{
	Speed 22
	Damage 2
}

ACTOR DragonAcid : DoomImpBall
{
	Speed 24
	Damage 8
	Scale 1.6
}

ACTOR AlienChaingunner : ChaingunGuy replaces ChaingunGuy
{
	BloodColor "30 D0 20"
	SeeSound "imp/sight"
	PainSound "demon/pain"
	DeathSound "imp/death"
	ActiveSound "imp/active"
	States
	{
	Missile:
		CPOS E 10 A_FaceTarget
		CPOS FE 4 Bright A_SpawnProjectile("SpitterAcid", 32, 0, random(-5, 5))
		CPOS F 1 A_CPosRefire
		Goto Missile+1
	}
}

ACTOR AlienQueen : SpiderMastermind replaces SpiderMastermind
{
	BloodColor "30 D0 20"
	States
	{
	Missile:
		SPID A 20 Bright A_FaceTarget
		SPID G 4 Bright A_SpawnProjectile("SpitterAcid", 36, 0, random(-6, 6))
		SPID H 4 Bright A_SpawnProjectile("SpitterAcid", 36, 0, random(-6, 6))
		SPID H 1 Bright A_SpidRefire
		Goto Missile+1
	}
}

ACTOR AlienWidow : Arachnotron replaces Arachnotron
{
	BloodColor "30 D0 20"
	States
	{
	Missile:
		BSPI A 20 Bright A_FaceTarget
		BSPI G 4 Bright A_SpawnProjectile("ArachnotronAcid", 24, 0, random(-4, 4))
		BSPI H 4 Bright
		BSPI H 1 Bright A_SpidRefire
		Goto Missile+1
	}
}

ACTOR AlienDragon : Cyberdemon replaces Cyberdemon
{
	BloodColor "30 D0 20"
	States
	{
	Missile:
		CYBR E 6 A_FaceTarget
		CYBR F 12 Bright A_SpawnProjectile("DragonAcid", 54, 0)
		CYBR E 12 A_FaceTarget
		CYBR F 12 Bright A_SpawnProjectile("DragonAcid", 54, 0)
		CYBR E 12 A_FaceTarget
		CYBR F 12 Bright A_SpawnProjectile("DragonAcid", 54, 0)
		Goto See
	}
}

ACTOR AlienSpitter : DoomImp replaces DoomImp
{
	BloodColor "30 D0 20"
	PainSound "demon/pain"
}

ACTOR AlienHugger : LostSoul replaces LostSoul
{
	DeathSound "alien/hugger_die"
}
"""
# The other aliens only need acid blood.
for _cls, _base in [("AlienRunner", "Demon"), ("AlienStalker", "Spectre"), ("AlienShrike", "Cacodemon"),
                    ("AlienCrusher", "BaronOfHell"), ("AlienWarrior", "HellKnight"), ("AlienHunter", "Revenant"),
                    ("AlienBoiler", "Fatso"), ("AlienCarrier", "PainElemental"), ("AlienPraetorian", "Archvile")]:
    DECORATE += f"\nACTOR {_cls} : {_base} replaces {_base}\n{{\n\tBloodColor \"30 D0 20\"\n}}\n"


def run(cmd):
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--freedoom", required=True)
    ap.add_argument("--iwad", required=True)
    args = ap.parse_args()
    out = os.path.abspath(args.out)
    wads = os.path.join(out, "wads")
    tmp = os.path.join(out, "alien_attacks_tmp")
    os.makedirs(wads, exist_ok=True)
    os.makedirs(tmp, exist_ok=True)
    py = [sys.executable, "-I"]

    parts = []
    for prefix in ("BAL2", "MANF", "FATB", "FIRE"):
        wad = os.path.join(tmp, f"{prefix}.wad")
        run(py + [os.path.join(HERE, "build_recolor.py"), "--freedoom", os.path.join(args.freedoom, "sprites"),
                  "--buildcfg", os.path.join(args.freedoom, "buildcfg.txt"), "--playpal", args.iwad,
                  "--prefix", prefix, "--out", wad])
        parts.append(wad)

    body = DECORATE.encode()
    deco_wad = os.path.join(tmp, "decorate.wad")
    with open(deco_wad, "wb") as f:
        f.write(struct.pack("<4sII", b"PWAD", 1, 12 + len(body)) + body + struct.pack("<II8s", 12, len(body), b"DECORATE"))
    run(py + [os.path.join(HERE, "merge_wads.py"), os.path.join(wads, "alien_attacks.wad")] + parts + [deco_wad])


if __name__ == "__main__":
    main()
