"""Build five SOM looks for the zombieman and shotgun guy slots, plus a GZDoom DECORATE random spawner.

Each look is its own sprite set (SOMA..SOME for the rifle slot, SOSA..SOSE for the shotgun slot) with
the same frame layout and anchors as POSS / SPOS. DECORATE defines one actor per look, and a
RandomSpawner replaces ZombieMan / ShotgunGuy so each spawn picks a look at random. GZDoom/UZDoom only.

usage: build_som_variants.py --out OUT_DIR --freedoom FREEDOOM_ROOT --iwad IWAD
  OUT_DIR is build_all.sh's output directory (needs tgmc_sprites/, compose_units.py and doomlib.py in it).
  Writes OUT_DIR/wads/som_variants.wad
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# look name: (uniform, boots, gloves, armor, helmet, rifle sheet:state, shotgun sheet:state)
LOOKS = {
    "light":   ("ert_uniforms:som_uniform", "feet:som", "hands:som", "som_armor:som_light_black",
                "som_helmets:som_helmet_light_black", "rifles_right_1:v31_w", "shotguns_right_1:v51_w"),
    "medium":  ("ert_uniforms:som_uniform", "feet:som", "hands:som", "som_armor:som_medium_black",
                "som_helmets:som_helmet_black", "rifles_right_1:v34_w", "shotguns_right_1:v51b_w"),
    "heavy":   ("ert_uniforms:som_uniform", "feet:som", "hands:som", "som_armor:som_heavy_black",
                "som_helmets:som_helmet_black", "machineguns_right_64:v41_w", "shotguns_right_1:v51_w"),
    "leader":  ("ert_uniforms:som_uniform_leader", "feet:som", "hands:som_veteran", "som_armor:som_leader_black",
                "som_helmets:som_helmet_leader_black", "rifles_right_1:v34_black_w", "shotguns_right_1:v10_w"),
    "officer": ("ert_uniforms:som_officer_uniform", "feet:som_officer_boots", "hands:som_officer_gloves",
                "som_armor:som_officer_black", "som_helmets:som_helmet_officer_black",
                "rifles_right_1:v35_w", "shotguns_right_1:v51b_w"),
}
LETTERS = "ABCDE"
# slot: (sprite prefix stem, Freedoom prefix to copy layout from, DECORATE class, weapon index in LOOKS)
SLOTS = {
    "rifle": ("SOM", "POSS", "ZombieMan", 5),
    "shotgun": ("SOS", "SPOS", "ShotgunGuy", 6),
}

ZOMBIE_STATES = """\
	Spawn:
		{s} AB 10 A_Look
		Loop
	See:
		{s} AABBCCDD 4 A_Chase
		Loop
	Missile:
		{s} E 10 A_FaceTarget
		{s} F 8 A_PosAttack
		{s} E 8
		Goto See
	Pain:
		{s} G 3
		{s} G 3 A_Pain
		Goto See
	Death:
		{s} H 5
		{s} I 5 A_Scream
		{s} J 5 A_NoBlocking
		{s} K 5
		{s} L -1
		Stop
	XDeath:
		{s} M 5
		{s} N 5 A_XScream
		{s} O 5 A_NoBlocking
		{s} PQRST 5
		{s} U -1
		Stop
	Raise:
		{s} LKJIH 5
		Goto See
"""

SHOTGUN_STATES = """\
	Spawn:
		{s} AB 10 A_Look
		Loop
	See:
		{s} AABBCCDD 3 A_Chase
		Loop
	Missile:
		{s} E 10 A_FaceTarget
		{s} F 10 Bright A_SposAttack
		{s} E 10
		Goto See
	Pain:
		{s} G 3
		{s} G 3 A_Pain
		Goto See
	Death:
		{s} H 5
		{s} I 5 A_Scream
		{s} J 5 A_NoBlocking
		{s} K 5
		{s} L -1
		Stop
	XDeath:
		{s} M 5
		{s} N 5 A_XScream
		{s} O 5 A_NoBlocking
		{s} PQRS 5
		{s} T 5
		{s} U -1
		Stop
	Raise:
		{s} LKJIH 5
		Goto See
"""


def run(cmd):
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--freedoom", required=True)
    ap.add_argument("--iwad", required=True)
    args = ap.parse_args()
    out = os.path.abspath(args.out)
    wads = os.path.join(out, "wads")
    tmp = os.path.join(out, "som_variants_tmp")
    os.makedirs(wads, exist_ok=True)
    os.makedirs(tmp, exist_ok=True)
    py = [sys.executable, "-I"]
    compose = os.path.join(out, "compose_units.py")

    decorate = ["// SOM variants: generated by build_som_variants.py\n"]
    parts = []
    for slot, (stem, like, cls, widx) in SLOTS.items():
        spawner = [f"ACTOR SOM{slot.capitalize()}Spawner : RandomSpawner replaces {cls}\n{{\n"]
        for letter, (look, spec) in zip(LETTERS, LOOKS.items()):
            uniform, boots, gloves, armor, helmet = spec[:5]
            weapon = spec[widx]
            gear = [uniform, boots, gloves, armor, helmet]
            armed = os.path.join(tmp, f"{slot}_{look}_dirs")
            dead = os.path.join(tmp, f"{slot}_{look}_dead_dirs")
            run(py + [compose, armed] + [f"x:{g}" for g in gear + [weapon]])
            run(py + [compose, dead] + [f"x:{g}" for g in gear])  # the weapon is dropped when they fall
            sprite = f"{stem}{letter}"
            wad = os.path.join(tmp, f"{sprite}.wad")
            run(py + [os.path.join(HERE, "build_sprites.py"), "--prefix", sprite, "--like", like, "--auto-frames",
                      "--d0", f"{armed}/d0.png", "--d1", f"{armed}/d1.png", "--d2", f"{armed}/d2.png",
                      "--d3", f"{armed}/d3.png", "--death-tilt-src", f"{dead}/d0.png", "--death-tilt-count", "5",
                      "--freedoom", os.path.join(args.freedoom, "sprites"),
                      "--buildcfg", os.path.join(args.freedoom, "buildcfg.txt"),
                      "--playpal", args.iwad, "--out", wad])
            parts.append(wad)
            actor = f"SOM_{slot}_{look}"
            states = (ZOMBIE_STATES if slot == "rifle" else SHOTGUN_STATES).format(s=sprite)
            decorate.append(f"\nACTOR {actor} : {cls}\n{{\n\tStates\n\t{{\n{states}\t}}\n}}\n")
            spawner.append(f'\tDropItem "{actor}"\n')
            print(f"built {sprite} ({slot} slot, {look})")
        spawner.append("}\n")
        decorate.append("\n" + "".join(spawner))

    deco_path = os.path.join(tmp, "DECORATE.txt")
    with open(deco_path, "w") as f:
        f.write("".join(decorate))
    # DECORATE lump goes in its own tiny WAD so merge_wads can place it after the sprites.
    deco_wad = os.path.join(tmp, "decorate.wad")
    import struct
    body = open(deco_path, "rb").read()
    with open(deco_wad, "wb") as f:
        entry = struct.pack("<II8s", 12, len(body), b"DECORATE")
        f.write(struct.pack("<4sII", b"PWAD", 1, 12 + len(body)) + body + entry)
    run(py + [os.path.join(HERE, "merge_wads.py"), os.path.join(wads, "som_variants.wad")] + parts + [deco_wad])


if __name__ == "__main__":
    main()
